// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/coach/efficient": {
            "get": {
                "description": "根据时间范围统计教练和校区的效率数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教练"
                ],
                "summary": "教练效率统计",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始时间，格式：2006-01-02 15:04:05",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间，格式：2006-01-02 15:04:05",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.EfficiencyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/course/total": {
            "get": {
                "description": "根据开始时间查询课程列表，支持按会员编号过滤和分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程"
                ],
                "summary": "查询课程列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始时间，格式：2006-01-02 15:04:05",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会员编号，可选",
                        "name": "number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码，从1开始，默认1",
                        "name": "pageNum",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.CoursePage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务是否正常运行",
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sms/notify": {
            "post": {
                "description": "按照课程查询用户并发送短信通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短信"
                ],
                "summary": "通知课程",
                "parameters": [
                    {
                        "description": "通知请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.NotifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.NotifyRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "课程ID，必填",
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "handler.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码，0表示成功",
                    "type": "integer",
                    "example": 0
                },
                "message": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.Charge": {
            "type": "object",
            "properties": {
                "annual_times": {
                    "type": "number"
                },
                "charge": {
                    "type": "number"
                },
                "charged_time": {
                    "type": "string"
                },
                "coach": {
                    "$ref": "#/definitions/model.Coach"
                },
                "coach_id": {
                    "type": "integer"
                },
                "court": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "notified": {
                    "type": "integer"
                },
                "prepaid_card": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.PrepaidCard"
                        }
                    ]
                },
                "prepaid_card_id": {
                    "description": "外键字段",
                    "type": "integer"
                },
                "times": {
                    "type": "number"
                },
                "worth": {
                    "type": "integer"
                }
            }
        },
        "model.Coach": {
            "type": "object",
            "properties": {
                "charges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Charge"
                    }
                },
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Course"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                }
            }
        },
        "model.Course": {
            "type": "object",
            "properties": {
                "coach": {
                    "$ref": "#/definitions/model.Coach"
                },
                "coach_id": {
                    "type": "integer"
                },
                "course_type": {
                    "description": "-2体验课未成单,-1体验课成单,0订场，1班课，2私教",
                    "type": "integer"
                },
                "court": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Court"
                        }
                    ]
                },
                "court_id": {
                    "description": "外键字段",
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_adult": {
                    "description": "1=成人课程, 0=儿童课程",
                    "type": "integer"
                },
                "member": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PrepaidCard"
                    }
                },
                "notified": {
                    "type": "integer"
                },
                "spend": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Spend"
                    }
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "model.Court": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Course"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.PrepaidCard": {
            "type": "object",
            "properties": {
                "adults": {
                    "type": "integer"
                },
                "annual_count": {
                    "type": "number"
                },
                "annual_expire_time": {
                    "type": "string"
                },
                "charges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Charge"
                    }
                },
                "courses": {
                    "description": "关联关系",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Course"
                    }
                },
                "court": {
                    "type": "string"
                },
                "equivalent_balance": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "rest_charge": {
                    "type": "number"
                },
                "spends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Spend"
                    }
                },
                "times_count": {
                    "type": "number"
                },
                "times_expire_time": {
                    "type": "string"
                },
                "younths": {
                    "type": "integer"
                }
            }
        },
        "model.Spend": {
            "type": "object",
            "properties": {
                "annual_times": {
                    "type": "number"
                },
                "charge": {
                    "description": "消费金额",
                    "type": "number"
                },
                "description": {
                    "description": "注意：保持为float32类型",
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "quantities": {
                    "type": "integer"
                },
                "times": {
                    "type": "number"
                }
            }
        },
        "service.AnalyseItem": {
            "type": "object",
            "properties": {
                "analyse": {
                    "type": "number"
                },
                "courses": {
                    "type": "number"
                },
                "deal": {
                    "type": "number"
                },
                "key": {
                    "type": "string"
                },
                "members": {
                    "type": "number"
                },
                "trial": {
                    "type": "number"
                },
                "workTime": {
                    "type": "number"
                }
            }
        },
        "service.CoursePage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Course"
                    }
                },
                "first": {
                    "type": "boolean"
                },
                "last": {
                    "type": "boolean"
                },
                "number": {
                    "type": "integer"
                },
                "numberOfElements": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "service.EfficiencyResponse": {
            "type": "object",
            "properties": {
                "analyse": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.AnalyseItem"
                    }
                },
                "revenue": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.RevenueItem"
                    }
                }
            }
        },
        "service.RevenueItem": {
            "type": "object",
            "properties": {
                "charge": {
                    "type": "number"
                },
                "equival": {
                    "type": "number"
                },
                "key": {
                    "type": "string"
                },
                "spend": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:31168",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Ledong DB API",
	Description:      "乐动数据库服务API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
