// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/coach/efficient": {
            "get": {
                "description": "根据时间范围统计教练和校区的效率数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教练"
                ],
                "summary": "教练效率统计",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始时间，格式：2006-01-02 15:04:05",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间，格式：2006-01-02 15:04:05",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.EfficiencyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/course/total": {
            "get": {
                "description": "根据开始时间查询课程列表，支持按会员编号过滤和分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程"
                ],
                "summary": "查询课程列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始时间，格式：2006-01-02 15:04:05",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会员编号，可选",
                        "name": "number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码，从1开始，默认1",
                        "name": "pageNum",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.CoursePage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务是否正常运行",
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/prepaidCard/course/create": {
            "post": {
                "description": "创建新课程，支持添加会员和消费记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程"
                ],
                "summary": "创建课程",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "startTime",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "endTime",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教练名称",
                        "name": "coachName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "format": "float32",
                        "description": "课程时长",
                        "name": "spendingTime",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "场地名称",
                        "name": "courtName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "描述",
                        "name": "descript",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "课程类型",
                        "name": "courseType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会员JSON对象",
                        "name": "membersObj",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "是否成人课程",
                        "name": "isAdult",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/prepaidCard/course/duplicate": {
            "post": {
                "description": "检查课程列表中是否有重复的课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程"
                ],
                "summary": "课程重复检查",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "description": "课程参数列表",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/prepaidCard/course/notify": {
            "post": {
                "description": "发送课程通知短信",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程"
                ],
                "summary": "课程通知",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "courseId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/prepaidCard/course/sm": {
            "post": {
                "description": "发送自定义短信",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程"
                ],
                "summary": "发送课程短信",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "短信参数",
                        "name": "params",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/prepaidCard/course/trial/{id}": {
            "post": {
                "description": "将体验课状态加1（从未成单变为成单）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程"
                ],
                "summary": "更新体验课状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/prepaidCard/course/{id}": {
            "delete": {
                "description": "删除课程并退还所有会员的消费",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程"
                ],
                "summary": "删除课程",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/prepaidCard/course/{id}/{member}": {
            "delete": {
                "description": "从课程中移除指定会员，并退还消费",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程"
                ],
                "summary": "移除课程成员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "课程ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会员编号",
                        "name": "member",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/prepaidCard/spend": {
            "get": {
                "description": "查询消费记录，支持按会员编号过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消费记录"
                ],
                "summary": "查询消费记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会员编号，可选",
                        "name": "number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.SpendPage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/sms/notify": {
            "post": {
                "description": "按照课程查询用户并发送短信通知",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "短信"
                ],
                "summary": "通知课程",
                "parameters": [
                    {
                        "description": "通知请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.NotifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/": {
            "get": {
                "description": "根据会员编号查询单个会员，或查询所有会员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查询会员列表或单个会员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会员编号",
                        "name": "number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PrepaidCard"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/charged": {
            "post": {
                "description": "为用户充值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "充值",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "会员编号",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "format": "float32",
                        "description": "充值金额",
                        "name": "charged",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "充值时间",
                        "name": "time",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "format": "float32",
                        "description": "充值次数",
                        "name": "times",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "format": "float32",
                        "description": "年卡次数",
                        "name": "annualTimes",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "年卡过期时间",
                        "name": "annualExpireTime",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "等值",
                        "name": "worth",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "场地",
                        "name": "court",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教练",
                        "name": "coach",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "备注",
                        "name": "description",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Charge"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/charged/coach/{number}": {
            "get": {
                "description": "根据教练编号和时间范围查询充值记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查询教练的充值记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "教练编号",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/charged/retreat/{id}": {
            "post": {
                "description": "根据充值记录ID进行退费",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "退费",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "充值记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/charged/total": {
            "get": {
                "description": "查询所有充值记录，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查询所有充值记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ChargePage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/charged/{number}": {
            "get": {
                "description": "根据会员编号查询充值记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查询某个用户的充值记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会员编号",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.ChargePage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/coach": {
            "get": {
                "description": "查询所有活跃的教练",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查询教练列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Coach"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/course/notify": {
            "post": {
                "description": "发送课程通知短信",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "课程通知",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "课程ID，可选，不传则通知所有未通知的课程",
                        "name": "id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/court": {
            "get": {
                "description": "查询所有场地",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "查询场地列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Court"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/member/{number}": {
            "post": {
                "description": "设置会员的青少年和成人数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "设置会员的青少年和成人数量",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会员编号",
                        "name": "number",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "青少年数量",
                        "name": "yonth",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "成人数量",
                        "name": "adult",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PrepaidCard"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "创建新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "安全验证头",
                        "name": "secure",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "会员编号",
                        "name": "number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "场地",
                        "name": "court",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.NotifyRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "课程ID，必填",
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "handler.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码，0表示成功",
                    "type": "integer",
                    "example": 0
                },
                "message": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.Charge": {
            "type": "object",
            "properties": {
                "annual_times": {
                    "type": "number"
                },
                "charge": {
                    "type": "number"
                },
                "charged_time": {
                    "type": "string"
                },
                "coach": {
                    "$ref": "#/definitions/model.Coach"
                },
                "coach_id": {
                    "type": "integer"
                },
                "court": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "notified": {
                    "type": "integer"
                },
                "prepaid_card": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.PrepaidCard"
                        }
                    ]
                },
                "prepaid_card_id": {
                    "description": "外键字段",
                    "type": "integer"
                },
                "times": {
                    "type": "number"
                },
                "worth": {
                    "type": "integer"
                }
            }
        },
        "model.Coach": {
            "type": "object",
            "properties": {
                "charges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Charge"
                    }
                },
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Course"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                }
            }
        },
        "model.Course": {
            "type": "object",
            "properties": {
                "coach": {
                    "$ref": "#/definitions/model.Coach"
                },
                "coach_id": {
                    "type": "integer"
                },
                "course_type": {
                    "description": "-2体验课未成单,-1体验课成单,0订场，1班课，2私教",
                    "type": "integer"
                },
                "court": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Court"
                        }
                    ]
                },
                "court_id": {
                    "description": "外键字段",
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_adult": {
                    "description": "1=成人课程, 0=儿童课程",
                    "type": "integer"
                },
                "member": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PrepaidCard"
                    }
                },
                "notified": {
                    "type": "integer"
                },
                "spend": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Spend"
                    }
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "model.Court": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Course"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.PrepaidCard": {
            "type": "object",
            "properties": {
                "adults": {
                    "type": "integer"
                },
                "annual_count": {
                    "type": "number"
                },
                "annual_expire_time": {
                    "type": "string"
                },
                "charges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Charge"
                    }
                },
                "courses": {
                    "description": "关联关系",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Course"
                    }
                },
                "court": {
                    "type": "string"
                },
                "equivalent_balance": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "rest_charge": {
                    "type": "number"
                },
                "spends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Spend"
                    }
                },
                "times_count": {
                    "type": "number"
                },
                "times_expire_time": {
                    "type": "string"
                },
                "younths": {
                    "type": "integer"
                }
            }
        },
        "model.Spend": {
            "type": "object",
            "properties": {
                "annual_times": {
                    "type": "number"
                },
                "charge": {
                    "description": "消费金额",
                    "type": "number"
                },
                "description": {
                    "description": "注意：保持为float32类型",
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "quantities": {
                    "type": "integer"
                },
                "times": {
                    "type": "number"
                }
            }
        },
        "service.AnalyseData": {
            "type": "object",
            "properties": {
                "analyse": {
                    "type": "number"
                },
                "courses": {
                    "type": "number"
                },
                "deal": {
                    "type": "number"
                },
                "members": {
                    "type": "number"
                },
                "trial": {
                    "type": "number"
                },
                "workTime": {
                    "type": "number"
                }
            }
        },
        "service.ChargePage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Charge"
                    }
                },
                "first": {
                    "type": "boolean"
                },
                "last": {
                    "type": "boolean"
                },
                "number": {
                    "type": "integer"
                },
                "numberOfElements": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "service.CoursePage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Course"
                    }
                },
                "first": {
                    "type": "boolean"
                },
                "last": {
                    "type": "boolean"
                },
                "number": {
                    "type": "integer"
                },
                "numberOfElements": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "service.EfficiencyResponse": {
            "type": "object",
            "properties": {
                "analyse": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {
                            "$ref": "#/definitions/service.AnalyseData"
                        }
                    }
                },
                "revenue": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {
                            "$ref": "#/definitions/service.RevenueData"
                        }
                    }
                }
            }
        },
        "service.RevenueData": {
            "type": "object",
            "properties": {
                "charge": {
                    "type": "number"
                },
                "equival": {
                    "type": "number"
                },
                "spend": {
                    "type": "number"
                }
            }
        },
        "service.SpendPage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Spend"
                    }
                },
                "first": {
                    "type": "boolean"
                },
                "last": {
                    "type": "boolean"
                },
                "number": {
                    "type": "integer"
                },
                "numberOfElements": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:31168",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Ledong DB API",
	Description:      "乐动数据库服务API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
